### ISSUE TITLE
[Bug]: verify codes is a transaction?

### ISSUE THREAD

**Issue by gregoriocanal** [IHE/ITI.Finance#12]
### Contact Details

gcanal@consorzioarsenal.it

### Section Number

in Figure 1:XX.4.2.2.2-1:

### What is wrong

in Figure 1:XX.4.2.2.2-1:
point [2] and [3] are a transaction between the coverage requestor and the claim manager?

### Priority

{"Medium"=>"Significant issue or clarification. Requires discussion, but should not lead to long debate."}

### Code of Conduct

- [X] I agree to follow the IHE Code of Conduct

**Comment by gregoriocanal** [comment]
same in Figure 1:XX.4.2.3.2-1.

Similar issue also in figure Figure 1:XX.4.2.4.2-1 and Figure 1:XX.4.2.5.2-1

**Comment by lukeaduncan** [comment]
Yes, this is an optional section where the requestor may lookup and verify codes to be used in the request.  It's not part of this profile and it may happen in different ways.  It's just showing an example for the use case.
