### ISSUE TITLE
[Bug]: FHIR Version 

### ISSUE THREAD

**Issue by gregoriocanal** [IHE/ITI.Finance#13]
### Contact Details

gcanal@consorzioarsenal.it

### What is wrong

This profile is base on FHIR R4, there is an explict reason why we didn't profile it in R5?
Financial is a an area that does not involve only healthcare vendors, that can be already bound to R4, but also other vendors that maybe are completly new to FHIR.

### Priority

{"Low"=>"Typo or other minor classification that an editor can manage. Requires no group discussion."}

### Code of Conduct

- [X] I agree to follow the IHE Code of Conduct

**Comment by lukeaduncan** [comment]
To align with other IHE profiles, we used R4 for this.  Otherwise we wouldn't be able to depend on BALP and use it.
