### ISSUE TITLE
[Bug]: EnrollmentRequest and EnrollmentResponse FMM

### ISSUE THREAD

**Issue by gregoriocanal** [IHE/ITI.Finance#14]
### Contact Details

gcanal@consorzioarsenal.it

### What is wrong

EnrollmentRequest and EnrollmentResponse FHIR resources have a 0 FMM in R4.

In R5 these resources stille have 0.
R6 (ballot 2) still have 0.

do we know if FHIR community it is interested in these resources? their FMM will increase?
If i remember correctly an IHE FHIR profile CAN'T become Normative as long as the resources within it are not also normative

### Priority

{"High"=>"Important issue where there is major issue to be resolved. Requires discussion and debate."}

### Code of Conduct

- [X] I agree to follow the IHE Code of Conduct

**Comment by lukeaduncan** [comment]
This will not be able to go to final text until those resources are normative.  But these are the only ones available that we can use.
