### ISSUE TITLE
[Bug]: ITI-yy2 response 

### ISSUE THREAD

**Issue by gregoriocanal** [IHE/ITI.Finance#15]
### Contact Details

gcanal@consorzioarsenal.it

### Section Number

YY1.4.2.2 

### What is wrong

"If the disposition of the enrollment can’t be handled synchronously, then the outcome element SHALL be set to queued and EnrollmentResponse SHALL include an id and persist on the Beneficiary Manager so that the [ITI-YY3 Check Enrollment Status](https://profiles.ihe.net/ITI/FAIS/1.0.0-comment/ITI-YY3.html) transaction can be used to get updates on the response."

In he asynchronous scenatio should we also give guidance on how the status element should be valued since it is a required element?

### Priority

{"Medium"=>"Significant issue or clarification. Requires discussion, but should not lead to long debate."}

### Code of Conduct

- [X] I agree to follow the IHE Code of Conduct

**Comment by lukeaduncan** [comment]
I can certainly add something on the status element, but it shouldn't really be affected by if it's queued or not.  It would be active regardless if it's queued or complete for the outcome.  Would it be helpful to say the status should be active in most cases?
