### ISSUE TITLE
[Bug]: FAIS-001

### ISSUE THREAD

**Issue by gregoriocanal** [IHE/ITI.Finance#16]
### Contact Details

gcanal@consorzioarsenal.it

### What is wrong

All the transactions in the security considerations already requires auditing (e.g YY1 YY2 YY3 YY4... )
So if not ATNA i think BALP?

### Priority

{"High"=>"Important issue where there is major issue to be resolved. Requires discussion and debate."}

### Code of Conduct

- [X] I agree to follow the IHE Code of Conduct

**Comment by gregoriocanal** [comment]
It Is not high

**Comment by lukeaduncan** [comment]
This does already depend on and use BALP so I don't think we need anything else, but we can leave this as an open issue for now just in case a need comes up around this.
