### ISSUE TITLE
Should Check Coverage Eligibility transaction have a separate initiator actor ?

### ISSUE THREAD

**Issue by gpavan19** [IHE/ITI.Finance#2]
Reading the Use Case #3: Check Coverage, seems to me that one system could implement this transaction only to check the coverage to evaluate if further proceed with the medical procedure on the patient, but not to necessarily submit a claim too.

So that, the Check Coverage Eligibility should have a separate initiator actor that is not the actor that manage the claims.

**Comment by lukeaduncan** [comment]
This was split into another actor, Coverage Requestor.
